PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX core:  <http://vivoweb.org/ontology/core#>

SELECT ?s ?fn ?mn ?ln
WHERE
{
  ?s rdf:type foaf:Person .
  optional { ?s foaf:firstName ?fn } .
  optional { ?s core:middleName ?mn } .
  optional { ?s foaf:lastName ?ln } .
}
order by ?ln
