<#-- $This file is distributed under the terms of the license in /doc/license.txt$ -->
<#-- List individuals in the requested class. -->

<#import "lib-list.ftl" as l>

    <section id="menupage-intro" role="region">
        <h2>${page.title}</h2>
	</section>
${stylesheets.add('<link rel="stylesheet" href="${urls.base}/css/browseIndex.css" />')}
<#assign pageurl = page.urlMapping>
<section class="individualList">
    
    <#if message??>
        <p>${message}</p>
    <#else>
    	
        <#assign pagination>
            <#if (pages?size > 1) >
                pages:
                <ul class="pagination">
                    <#list pages as page>
                     	
                        <#if page.selected>
                            <li class="selectedNavPage">${page.text}</li>
                        <#else>
                            <#-- RY Ideally the urls would be generated by the controller; see search-pagedResults.ftl -->
                            <li><a href="${urls.base}${pageurl}?${page.param}">${page.text}</a></li>
                        </#if>
                    </#list>
                    
                </ul>
            </#if>
        </#assign>
        
        ${pagination}
        
        <ul>
            <#list individuals as individual>
                <li>
                    <#assign moniker = individual.moniker!>
                    <a href="${individual.profileUrl}">${individual.name}</a><#if moniker?has_content> <span class="moniker">${moniker}</span></#if>
                    <#assign links = individual.links>
                    <#if links?has_content>
                        <ul class="individualData">
                            <@l.firstLastList>
                                <#list links as link>
                                    <li><a class="externalLink" href="${link.url}">${link.anchor}</a></li>
                                </#list>
                            </@l.firstLastList>
                        </ul>
                    </#if>
                </li>
            </#list>
        </ul>
        
        ${pagination}
    </#if>
</section> <!-- .individualList -->
        

    
