$! $This file is distributed under the terms of the license in /doc/license.txt$ !$

$doctype()$

$head()$

<body>
    <div id="wrap" class="container">
        <div id="header">
            $identity()$
            $!  $menu()$ !$

        </div> <!-- header --> 
        
        <hr class="hidden" />
        
        <div id="contentwrap">       
            $body$    
        </div> <!-- contentwrap -->
    
        $footer()$
    
    </div> <!-- wrap -->
</body>
</html>
