package edu.cornell.mannlib.vitro.webapp.auth.attributes;

public enum AccessObjectType {
    CLASS,
    NAMED_OBJECT,
    DATA_PROPERTY,
    OBJECT_PROPERTY,
    DATA_PROPERTY_STATEMENT,
    OBJECT_PROPERTY_STATEMENT,
    ENTITY_URI,
    ROOT_USER,
    FAUX_OBJECT_PROPERTY,
    FAUX_DATA_PROPERTY,
    FAUX_DATA_PROPERTY_STATEMENT,
    FAUX_OBJECT_PROPERTY_STATEMENT,
}
